# Generated by Django 3.2.7 on 2021-11-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelibrary',
            name='fiiles',
            field=models.FileField(default=True, upload_to='File/product'),
            preserve_default=False,
        ),
    ]
