# Generated by Django 3.2.7 on 2021-11-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_imagelibrary_fiiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelibrary',
            old_name='fiiles',
            new_name='files',
        ),
    ]
