# Generated by Django 3.2.7 on 2021-11-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_imagelibrary_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usedFor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='App.usedfor'),
            preserve_default=False,
        ),
    ]
